/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*;
import java.io.*;
import javax.swing.JOptionPane;
/**
 *
 * @author andersonsantos
 */
public class BuscarCompras extends javax.swing.JInternalFrame {
    File clientesCad = new File("./src/Arquivos/clientesCadastrados.txt");
    File comprasCliente = new File("./src/Arquivos/VendasConcluidas.txt");
    ManipularArquivo imprimirNome = new ManipularArquivo();
    ManipularArquivo imprimirCpf = new ManipularArquivo();
    String comprasFeitas = "";
    String clienteBusca = "";
    String codigoB = "";

    /**
     * Creates new form BuscarCompras
     */
    public BuscarCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bucarCod = new javax.swing.JFormattedTextField();
        buscarC = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoCliente = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        comprasRealizadas = new javax.swing.JTextArea();
        okBusca = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(854, 598));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(95, 94, 94));
        jLabel1.setText("BUSCAR CLIENTE");
        jLabel1.setMaximumSize(new java.awt.Dimension(242, 26));
        jLabel1.setMinimumSize(new java.awt.Dimension(242, 26));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(95, 94, 94));
        jLabel2.setText("DIGITE O CÓDIGO DO CLIENTE:");

        bucarCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bucarCodActionPerformed(evt);
            }
        });

        buscarC.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        buscarC.setForeground(new java.awt.Color(95, 94, 94));
        buscarC.setText("BUSCAR");
        buscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCActionPerformed(evt);
            }
        });

        infoCliente.setEditable(false);
        infoCliente.setColumns(20);
        infoCliente.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        infoCliente.setForeground(new java.awt.Color(95, 94, 94));
        infoCliente.setRows(5);
        jScrollPane2.setViewportView(infoCliente);

        comprasRealizadas.setEditable(false);
        comprasRealizadas.setColumns(20);
        comprasRealizadas.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        comprasRealizadas.setRows(5);
        jScrollPane1.setViewportView(comprasRealizadas);

        okBusca.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        okBusca.setText("OK");
        okBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBuscaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jButton1.setText("CORRIGIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jButton2.setText("VOLTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(26, 26, 26)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(okBusca))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bucarCod, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buscarC)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bucarCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarC))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(okBusca)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(0, 142, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bucarCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bucarCodActionPerformed
        // TODO add your handling code here:
        codigoB = bucarCod.getText();
    }//GEN-LAST:event_bucarCodActionPerformed

    private void buscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCActionPerformed
        // TODO add your handling code here:
        int posicao = 0;
        try {
            FileReader listarFile = new FileReader(clientesCad);
            BufferedReader listarBuff = new BufferedReader(listarFile);
            FileReader listarCompra = new FileReader(comprasCliente);
            BufferedReader listarCompraB = new BufferedReader(listarFile);
            imprimirNome.mapearArquivo(clientesCad);
            imprimirCpf.mapearArquivo(clientesCad);
            for (int i = 0; i < clientesCad.length(); i++) {
                String linhaL = listarBuff.readLine();
                if(codigoB.equals(linhaL)){
                    posicao = i + 1;
                    imprimirNome.setClienteEncontrado(posicao);
                    imprimirCpf.setClienteEncontrado(posicao + 1);
                    clienteBusca = codigoB + "\n" + imprimirNome.getClienteEncontrado() +
                    "\n" + imprimirCpf.getClienteEncontrado();
                    infoCliente.append(clienteBusca);
                    JOptionPane.showMessageDialog(null, "Cliente encontrado!");
                }
            }
            listarBuff.close();
            listarFile.close();
        } catch (IOException except) {
            except.printStackTrace();
        }
    }//GEN-LAST:event_buscarCActionPerformed

    private void okBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBuscaActionPerformed
        // TODO add your handling code here:
        try {
            FileReader listarFile = new FileReader(comprasCliente);
            BufferedReader listarBuff = new BufferedReader(listarFile);
            imprimirNome.mapearArquivo(comprasCliente);
            imprimirCpf.mapearArquivo(comprasCliente);
            for (int i = 0; i < comprasCliente.length(); i++) {
                String linhaL = listarBuff.readLine();
                if(("CF3A" + codigoB + "NF4B").equals(linhaL)){
                    int posicao = i + 1;
                    imprimirNome.setClienteEncontrado(posicao);
                    imprimirCpf.setClienteEncontrado(posicao + 1);
                    clienteBusca = ("NUMERO DA NOTA FISCAL: CF3A" + codigoB + "NF4B") + "\n" + imprimirNome.getClienteEncontrado() +
                    "\n" + imprimirCpf.getClienteEncontrado();
                    comprasRealizadas.append(clienteBusca);
                    JOptionPane.showMessageDialog(null, "Cliente encontrado!");
                }
            }
            listarBuff.close();
            listarFile.close();
        } catch (IOException except) {
            except.printStackTrace();
        }
    }//GEN-LAST:event_okBuscaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        infoCliente.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField bucarCod;
    private javax.swing.JButton buscarC;
    private javax.swing.JTextArea comprasRealizadas;
    private javax.swing.JTextArea infoCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton okBusca;
    // End of variables declaration//GEN-END:variables
}
