package FrontEnd;
import BackEnd.Cliente;
import java.util.*;
import java.io.*;
import javax.swing.JOptionPane;
/**
 *
 * @author andersonsantos
 */
public class CadastrarCliente extends javax.swing.JFrame {
    File clientesCad = new File("./src/Arquivos/clientesCadastrados.txt");
    Cliente clienteC = new Cliente();
    Random rand = new Random();
    
    /**
     * Creates new form CadastrarCliente
     */
    public CadastrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        voltarC = new javax.swing.JButton();
        cadastrarC = new javax.swing.JButton();
        nomeC = new javax.swing.JTextField();
        cpfC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sobrenomeC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(95, 94, 94));
        jLabel1.setText("CADASTRO DE CLIENTE");

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(95, 94, 94));
        jLabel2.setText("NOME:");

        jLabel3.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(95, 94, 94));
        jLabel3.setText("CPF:");

        voltarC.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        voltarC.setForeground(new java.awt.Color(95, 94, 94));
        voltarC.setText("VOLTAR");
        voltarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCActionPerformed(evt);
            }
        });

        cadastrarC.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        cadastrarC.setForeground(new java.awt.Color(95, 94, 94));
        cadastrarC.setText("CADASTRAR");
        cadastrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCActionPerformed(evt);
            }
        });

        nomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCActionPerformed(evt);
            }
        });

        cpfC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfCActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(95, 94, 94));
        jLabel4.setText("SOBRENOME:");

        sobrenomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobrenomeCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeC)
                    .addComponent(cpfC)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(voltarC)
                                .addGap(60, 60, 60)
                                .addComponent(cadastrarC))
                            .addComponent(jLabel4))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(sobrenomeC))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sobrenomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarC)
                    .addComponent(cadastrarC))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_voltarCActionPerformed

    private void nomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCActionPerformed
        // TODO add your handling code here:
        clienteC.setCodigo(rand.nextInt(9999));
        int numNome = nomeC.getText().length();
        char[] verificaNome = nomeC.getText().toCharArray();
        boolean ver = true;
        for(int i = 0; i < verificaNome.length; i++){
            if(!Character.isLetter(verificaNome[i])){
                ver = false;
            }
        }
        if(numNome < 2){
            JOptionPane.showMessageDialog(null, "Nome inválido, por favor, digite novamente!");
        }
        else if(ver == false){
            JOptionPane.showMessageDialog(null, "O nome não pode conter numeros ou caracteres especiais, por favor, digite novamente!");
        }
        else{
            clienteC.setNome(nomeC.getText());
        }
    }//GEN-LAST:event_nomeCActionPerformed

    private void cpfCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfCActionPerformed
        // TODO add your handling code here:
        int numCpf = cpfC.getText().length();
        char[] verificaCpf = cpfC.getText().toCharArray();
        boolean ver = true;
        for(int i = 0; i < verificaCpf.length; i++){
            if(!Character.isDigit(verificaCpf[i])){
                ver = false;
            }
        }
        if(numCpf != 11){
            JOptionPane.showMessageDialog(null, "O numero do CPF deve conter 11 digitos, por favor, digite novamente!");
        }
        else if(ver == false){
            JOptionPane.showMessageDialog(null, "O numero do CPF deve conter apenas numeros, por favor, digite novamente!");
        }
        else{
            clienteC.setCpf(Long.parseLong(cpfC.getText()));
        }
    }//GEN-LAST:event_cpfCActionPerformed

    private void cadastrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCActionPerformed
        // TODO add your handling code here:
        try{
            FileWriter cadastrarFile = new FileWriter(clientesCad, true);
            BufferedWriter cadastrarBuff = new BufferedWriter(cadastrarFile);
            cadastrarBuff.write("\n" + "\n" + clienteC.getCodigo() + 
                                "\nNome: " + clienteC.getNome() + " " + clienteC.getSobrenome() +
                                "\nCPF: " + clienteC.getCpf());
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
            cadastrarBuff.close();
            cadastrarFile.close();
            dispose();
        }catch (IOException except){
            except.printStackTrace();
        }
    }//GEN-LAST:event_cadastrarCActionPerformed

    private void sobrenomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobrenomeCActionPerformed
        // TODO add your handling code here:
        int numNome = sobrenomeC.getText().length();
        char[] verificaNome = sobrenomeC.getText().toCharArray();
        boolean ver = true;
        for(int i = 0; i < verificaNome.length; i++){
            if(!Character.isLetter(verificaNome[i])){
                ver = false;
            }
        }
        if(numNome <= 2){
            JOptionPane.showMessageDialog(null, "Sobrenome inválido, por favor, digite novamente!");
        }
        else if(ver == false){
            JOptionPane.showMessageDialog(null, "O sobrenome não pode conter numeros ou caracteres especiais, por favor, digite novamente!");
        }
        else{
            clienteC.setSobrenome(sobrenomeC.getText());
        }
    }//GEN-LAST:event_sobrenomeCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarC;
    private javax.swing.JTextField cpfC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nomeC;
    private javax.swing.JTextField sobrenomeC;
    private javax.swing.JButton voltarC;
    // End of variables declaration//GEN-END:variables
}
