/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*;
import java.io.*;
import java.util.*;
/**
 *
 * @author andersonsantos
 */
public class ListarRemovidos extends javax.swing.JInternalFrame {
    File clientesRem = new File("./src/Arquivos/clientesRemovidos.txt");
    //String removidos = null;

    /**
     * Creates new form ListarRemovidos
     */
    public ListarRemovidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imprimeRem = new javax.swing.JButton();
        voltarR = new javax.swing.JButton();
        listaRE = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(894, 598));

        imprimeRem.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        imprimeRem.setForeground(new java.awt.Color(95, 94, 94));
        imprimeRem.setText("IMPRIMIR");
        imprimeRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimeRemActionPerformed(evt);
            }
        });

        voltarR.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        voltarR.setForeground(new java.awt.Color(95, 94, 94));
        voltarR.setText("VOLTAR");
        voltarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarRActionPerformed(evt);
            }
        });

        listaRE.setBackground(new java.awt.Color(166, 166, 166));
        listaRE.setEditable(false);
        listaRE.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        listaRE.setForeground(new java.awt.Color(1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(95, 94, 94));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTA DE CLIENTES REMOVIDOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listaRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(imprimeRem)
                .addGap(111, 111, 111)
                .addComponent(voltarR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imprimeRem)
                    .addComponent(voltarR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaRE, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imprimeRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimeRemActionPerformed
        // TODO add your handling code here:
        ManipularArquivo listarR = new ManipularArquivo();
        try{
            listarR.lerArquivo(clientesRem);
        }catch(IOException except){
            except.printStackTrace();
        }
        listaRE.append(listarR.getObjetosRetornados());
    }//GEN-LAST:event_imprimeRemActionPerformed

    private void voltarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarRActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_voltarRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarRemovidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarRemovidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarRemovidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarRemovidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarRemovidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton imprimeRem;
    private javax.swing.JLabel jLabel1;
    private java.awt.TextArea listaRE;
    private javax.swing.JButton voltarR;
    // End of variables declaration//GEN-END:variables
}
