/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*;
import java.io.*;
import java.text.*;
import javax.swing.JOptionPane;
/**
 *
 * @author andersonsantos
 */
public class NovaVenda extends javax.swing.JInternalFrame {
    DecimalFormat formatar = new DecimalFormat("0.00");
    File clientesCad = new File("./src/Arquivos/clientesCadastrados.txt");
    File vendasConcluidas = new File("./src/Arquivos/VendasConcluidas.txt");
    ManipularArquivo imprimirNome = new ManipularArquivo();
    ManipularArquivo imprimirCpf = new ManipularArquivo();
    String salvarCompra;
    String codigoClienteB;
    String clienteBusca;
    String categoriaProd;
    String produtoCompra;
    String precoProduto;
    String quantidadeProduto;
    String totalCarrinhoP;
    double total = 0.0;
    double camiseta = 99.90;
    double calca = 175.90;
    double sapato = 250.00;
    /**
     * Creates new form NovaVenda
     */
    public NovaVenda() {
        this.salvarCompra = "";
        this.codigoClienteB = "";
        this.clienteBusca = "";
        this.categoriaProd = "";
        this.produtoCompra = "";
        this.precoProduto = "";
        this.quantidadeProduto = "";
        this.totalCarrinhoP = "";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quantidadeProdutos = new javax.swing.JSpinner();
        codigoCliente = new javax.swing.JTextField();
        buscarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        quantidadeCarrinho = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        produtoCarrinho = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        precoCarrinho = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        totalCarrinho = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        confirmarItem = new javax.swing.JButton();
        cancelarVenda = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        infoClienteB = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        categoriaProduto = new javax.swing.JTextField();
        produtoVenda = new javax.swing.JTextField();
        confirmaCliente = new javax.swing.JButton();
        corrigirCliente = new javax.swing.JButton();
        confirmarVenda = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        okCategoria = new javax.swing.JButton();
        okProduto = new javax.swing.JButton();
        voltarVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(894, 598));

        quantidadeProdutos.setFont(new java.awt.Font("Century Schoolbook L", 1, 12)); // NOI18N
        quantidadeProdutos.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        quantidadeProdutos.setEnabled(false);

        codigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoClienteActionPerformed(evt);
            }
        });

        buscarCliente.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        buscarCliente.setText("BUSCAR");
        buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteActionPerformed(evt);
            }
        });

        quantidadeCarrinho.setEditable(false);
        quantidadeCarrinho.setColumns(3);
        quantidadeCarrinho.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        quantidadeCarrinho.setForeground(new java.awt.Color(1, 1, 1));
        quantidadeCarrinho.setRows(5);
        jScrollPane1.setViewportView(quantidadeCarrinho);

        produtoCarrinho.setEditable(false);
        produtoCarrinho.setColumns(20);
        produtoCarrinho.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        produtoCarrinho.setForeground(new java.awt.Color(1, 1, 1));
        produtoCarrinho.setRows(5);
        jScrollPane2.setViewportView(produtoCarrinho);

        precoCarrinho.setEditable(false);
        precoCarrinho.setColumns(5);
        precoCarrinho.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        precoCarrinho.setForeground(new java.awt.Color(1, 1, 1));
        precoCarrinho.setRows(5);
        jScrollPane3.setViewportView(precoCarrinho);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        totalCarrinho.setEditable(false);
        totalCarrinho.setColumns(20);
        totalCarrinho.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        totalCarrinho.setRows(5);
        jScrollPane4.setViewportView(totalCarrinho);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jLabel1.setText("Qtd.");

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jLabel2.setText("PRODUTO");

        jLabel3.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jLabel3.setText("PREÇO");

        jLabel4.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jLabel4.setText("TOTAL");

        confirmarItem.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        confirmarItem.setText("CONFIRMAR");
        confirmarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarItemActionPerformed(evt);
            }
        });

        cancelarVenda.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        cancelarVenda.setText("CANCELAR");
        cancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarVendaActionPerformed(evt);
            }
        });

        infoClienteB.setEditable(false);
        infoClienteB.setColumns(15);
        infoClienteB.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        infoClienteB.setForeground(new java.awt.Color(1, 1, 1));
        infoClienteB.setRows(4);
        jScrollPane5.setViewportView(infoClienteB);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(95, 94, 94));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SISTEMA DE VENDA");
        jLabel5.setMaximumSize(new java.awt.Dimension(242, 26));
        jLabel5.setMinimumSize(new java.awt.Dimension(242, 26));

        categoriaProduto.setEditable(false);
        categoriaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaProdutoActionPerformed(evt);
            }
        });

        produtoVenda.setEditable(false);
        produtoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoVendaActionPerformed(evt);
            }
        });

        confirmaCliente.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        confirmaCliente.setText("CONFIRMA");
        confirmaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaClienteActionPerformed(evt);
            }
        });

        corrigirCliente.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        corrigirCliente.setText("CORRIGE");
        corrigirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corrigirClienteActionPerformed(evt);
            }
        });

        confirmarVenda.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        confirmarVenda.setText("CONFIRMAR");
        confirmarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarVendaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jLabel6.setText("DIGITE O CÓDIGO DO CLIENTE:");

        jLabel7.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jLabel7.setText("DIGITE A CATEGORIA DO PRODUTO");

        jLabel8.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jLabel8.setText("DIGITE O CÓDIGO DO PRODUTO:");

        okCategoria.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        okCategoria.setText("OK");
        okCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okCategoriaActionPerformed(evt);
            }
        });

        okProduto.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        okProduto.setText("OK");
        okProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okProdutoActionPerformed(evt);
            }
        });

        voltarVenda.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        voltarVenda.setText("VOLTAR");
        voltarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(confirmarItem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(voltarVenda))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(produtoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(okProduto)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(codigoCliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buscarCliente))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(confirmaCliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(corrigirCliente))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(categoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(okCategoria)))
                            .addComponent(jLabel7)
                            .addComponent(quantidadeProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(57, 103, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(confirmarVenda)
                                .addGap(18, 18, 18)
                                .addComponent(cancelarVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buscarCliente)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmaCliente)
                            .addComponent(corrigirCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(okCategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(produtoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(okProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantidadeProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(confirmarVenda)
                        .addComponent(cancelarVenda)
                        .addComponent(confirmarItem)
                        .addComponent(voltarVenda)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoClienteActionPerformed
        // TODO add your handling code here:
        codigoClienteB = codigoCliente.getText();
        salvarCompra = "CF3A" + codigoClienteB + "NF4B";
    }//GEN-LAST:event_codigoClienteActionPerformed

    private void buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteActionPerformed
        // TODO add your handling code here:
        int posicao = 0;
        try { 
            FileReader listarFile = new FileReader(clientesCad);
            BufferedReader listarBuff = new BufferedReader(listarFile);
            imprimirNome.mapearArquivo(clientesCad);
            imprimirCpf.mapearArquivo(clientesCad);
            for (int i = 0; i < clientesCad.length(); i++) {
                String linhaL = listarBuff.readLine();
                if(codigoClienteB.equals(linhaL)){
                    posicao = i + 1;
                    imprimirNome.setClienteEncontrado(posicao);
                    imprimirCpf.setClienteEncontrado(posicao + 1);
                }
            }
            if(posicao == 0){
                JOptionPane.showMessageDialog(null, "Nenhum Cliente encontrado");
            }
            else{
                clienteBusca = codigoClienteB + "\n" + imprimirNome.getClienteEncontrado() + 
                                                "\n" + imprimirCpf.getClienteEncontrado();
                infoClienteB.append(clienteBusca);
            }
            listarBuff.close();
            listarFile.close();
        } catch (IOException except) {
                except.printStackTrace();
        }
    }//GEN-LAST:event_buscarClienteActionPerformed

    private void categoriaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaProdutoActionPerformed
        // TODO add your handling code here:
        categoriaProd = categoriaProduto.getText();
    }//GEN-LAST:event_categoriaProdutoActionPerformed

    private void confirmarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarItemActionPerformed
        // TODO add your handling code here:
        quantidadeProduto = quantidadeProdutos.getValue().toString();
        int quantidade = Integer.parseInt(quantidadeProduto);
        if(produtoCompra.equals("Camisa")){
            precoProduto += camiseta*quantidade;
            total += camiseta*quantidade;
        }
        else if(produtoCompra.equals("Calça")){
                precoProduto += calca*quantidade;
                total += calca*quantidade;
        }
        else if(produtoCompra.equals("Sapato")){
                precoProduto += sapato*quantidade;
                total += sapato*quantidade;
        }
        else{
            JOptionPane.showMessageDialog(null, "Produto enviado para o carrinho!");
        }
        totalCarrinhoP = formatar.format(total);
        quantidadeCarrinho.append(quantidadeProduto + "\n");
        produtoCarrinho.append(produtoCompra + "\n");
        precoCarrinho.append(precoProduto + "\n");
        totalCarrinho.setText(totalCarrinhoP);
        salvarCompra += "\n\tQUANTIDADE: " + quantidadeProduto + 
                        "\n\tPRODUTO: " + produtoCompra +
                        "\n\tTOTAL PRODUTO: " + precoProduto;
        produtoVenda.setText(null);
        categoriaProduto.setText(null);
        quantidadeProdutos.setValue(1);
        precoProduto = "";
    }//GEN-LAST:event_confirmarItemActionPerformed

    private void produtoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoVendaActionPerformed
        // TODO add your handling code here:}
        produtoCompra = produtoVenda.getText();
    }//GEN-LAST:event_produtoVendaActionPerformed

    private void corrigirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corrigirClienteActionPerformed
        // TODO add your handling code here:
        infoClienteB.setText(null);
    }//GEN-LAST:event_corrigirClienteActionPerformed

    private void confirmaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaClienteActionPerformed
        // TODO add your handling code here:
        if(!infoClienteB.equals(null)){
            categoriaProduto.setEditable(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Nenhum cliente encontrado.");
        }
    }//GEN-LAST:event_confirmaClienteActionPerformed

    private void okCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okCategoriaActionPerformed
        // TODO add your handling code here:
        produtoVenda.setEditable(true);
    }//GEN-LAST:event_okCategoriaActionPerformed

    private void okProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okProdutoActionPerformed
        // TODO add your handling code here:
        quantidadeProdutos.setEnabled(true);
    }//GEN-LAST:event_okProdutoActionPerformed

    private void cancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarVendaActionPerformed
        // TODO add your handling code here:
        quantidadeCarrinho.setText(null);
        produtoCarrinho.setText(null);
        precoCarrinho.setText(null);
        totalCarrinho.setText(null);
        produtoVenda.setText(null);
        categoriaProduto.setText(null);
        quantidadeProdutos.setValue(1);
    }//GEN-LAST:event_cancelarVendaActionPerformed

    private void voltarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarVendaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_voltarVendaActionPerformed

    private void confirmarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarVendaActionPerformed
        // TODO add your handling code here:
        if(quantidadeCarrinho == null){
            JOptionPane.showMessageDialog(null, "Quantidade nula, recomece a venda!");
        }
        else if(produtoCarrinho == null){
            JOptionPane.showMessageDialog(null, "Sem produtos no Carrinho, recomece a venda!");
        }
        else if(precoCarrinho == null){
            JOptionPane.showMessageDialog(null, "Não existe preço no Carrinho, recomece a venda!");
        }
        else{
            ManipularArquivo escreveCompra = new ManipularArquivo();
            try{
                salvarCompra += "\n\n\tTOTAL COMPRA: " + totalCarrinhoP + ";\n";
                escreveCompra.escreverArquivo(vendasConcluidas, salvarCompra);
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                dispose();
            }catch(IOException except){
                except.printStackTrace();
            }
        }
    }//GEN-LAST:event_confirmarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarCliente;
    private javax.swing.JButton cancelarVenda;
    private javax.swing.JTextField categoriaProduto;
    private javax.swing.JTextField codigoCliente;
    private javax.swing.JButton confirmaCliente;
    private javax.swing.JButton confirmarItem;
    private javax.swing.JButton confirmarVenda;
    private javax.swing.JButton corrigirCliente;
    private javax.swing.JTextArea infoClienteB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton okCategoria;
    private javax.swing.JButton okProduto;
    private javax.swing.JTextArea precoCarrinho;
    private javax.swing.JTextArea produtoCarrinho;
    private javax.swing.JTextField produtoVenda;
    private javax.swing.JTextArea quantidadeCarrinho;
    private javax.swing.JSpinner quantidadeProdutos;
    private javax.swing.JTextArea totalCarrinho;
    private javax.swing.JButton voltarVenda;
    // End of variables declaration//GEN-END:variables
}
