/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*;
import java.io.*;
import javax.swing.JOptionPane;
import java.io.File;

/**
 *
 * @author Alexandro
 */
public class ProdutosExcluidos extends javax.swing.JInternalFrame {
    File produtoCad = new File("./src/arquivos/produtosCadastrados.txt");
    File produtoRem = new File("./src/arquivos/produtosRemovido.txt");
    String codigoP = null;
     String dadosProdutos = " ";
         ManipularArquivoProduto imprimirNome = new ManipularArquivoProduto();
         ManipularArquivoProduto imprimirPrecoVenda = new ManipularArquivoProduto();
         ManipularArquivoProduto imprimirPrecoCusto = new ManipularArquivoProduto();
         ManipularArquivoProduto imprimirQuantidade = new ManipularArquivoProduto();
         ManipularArquivoProduto imprimirFornecedor = new ManipularArquivoProduto();
         String produtoBusca = null;
    /**
     * Creates new form ProdutosExcluidos
     */
    public ProdutosExcluidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoproduto = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buscarcodigop = new javax.swing.JButton();
        excluirp = new javax.swing.JButton();
        buscarp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(894, 598));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(95, 94, 94));
        jLabel1.setText("PRODUTOS EXCLUÍDOS");

        infoproduto.setEditable(false);
        infoproduto.setBackground(new java.awt.Color(153, 153, 153));
        infoproduto.setColumns(20);
        infoproduto.setRows(5);
        infoproduto.setDisabledTextColor(new java.awt.Color(95, 94, 94));
        jScrollPane1.setViewportView(infoproduto);

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(95, 94, 94));
        jButton1.setText("VOLTAR");
        jButton1.setAutoscrolls(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(95, 94, 94));
        jLabel2.setText("DIGITE O CODIGO DO PRODUTO QUE DESEJA EXCLUIR: ");

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(95, 94, 94));
        jLabel3.setText("LISTA PRODUTOS  EXCLUIDOS: ");

        buscarcodigop.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        buscarcodigop.setForeground(new java.awt.Color(95, 94, 94));
        buscarcodigop.setText("BUSCAR");
        buscarcodigop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarcodigopActionPerformed(evt);
            }
        });

        excluirp.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        excluirp.setForeground(new java.awt.Color(95, 94, 94));
        excluirp.setText("EXCLUIR");
        excluirp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirpActionPerformed(evt);
            }
        });

        buscarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(86, 86, 86)
                        .addComponent(excluirp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buscarp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarcodigop)))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buscarcodigop))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(excluirp))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscarcodigopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarcodigopActionPerformed
        
       
        int posicao = 0;
        codigoP = buscarp.getText();
       
         
        try {
            FileReader listarFile = new FileReader(produtoCad);
            BufferedReader listarBuff = new BufferedReader(listarFile);
            
            imprimirNome.mapearArquivo(produtoCad);
            imprimirPrecoVenda.mapearArquivo(produtoCad);
            imprimirPrecoCusto.mapearArquivo(produtoCad);
            imprimirQuantidade.mapearArquivo(produtoCad);
            imprimirFornecedor.mapearArquivo(produtoCad);
             
            
            for ( int i = 0 ; i < produtoCad.length() ; i++ ) {
                String linhaL = listarBuff.readLine();
                if(("CODIGO: " + codigoP).equals(linhaL)){
                    JOptionPane.showMessageDialog(null, "Produto encontrado!");
                    posicao = i + 1;
                    
                    imprimirNome.setProdutoEncontrado(posicao);
                    imprimirPrecoVenda.setProdutoEncontrado(posicao +1);
                    imprimirPrecoCusto.setProdutoEncontrado(posicao + 2);
                    imprimirQuantidade.setProdutoEncontrado(posicao + 3);
                    imprimirFornecedor.setProdutoEncontrado(posicao + 4);
                    
                    dadosProdutos = codigoP + "\n"+imprimirNome.getProdutoEncontrado() + "\n" 
                               + imprimirPrecoVenda.getProdutoEncontrado() +
                                    "\n" + imprimirPrecoCusto.getProdutoEncontrado() + "\n" +
                                        imprimirQuantidade.getProdutoEncontrado() +"\n" + 
                                            imprimirFornecedor.getProdutoEncontrado();
                    
                    
                }
                
            }
            infoproduto.append(dadosProdutos); 
            JOptionPane.showMessageDialog(null, dadosProdutos);
            listarBuff.close();
            listarFile.close();
        }   catch (IOException except) {
                except.printStackTrace();
            }
      
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarcodigopActionPerformed

    private void buscarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarpActionPerformed

    private void excluirpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirpActionPerformed
        int posicao = 0;
         try {
             
             imprimirNome.mapearArquivo(produtoRem);
             imprimirPrecoVenda.mapearArquivo(produtoRem);
             imprimirPrecoCusto.mapearArquivo(produtoRem);
             imprimirQuantidade.mapearArquivo(produtoRem);
             imprimirFornecedor.mapearArquivo(produtoRem);
             String objetoP = ( dadosProdutos );
             ManipularArquivoProduto cadastro = new ManipularArquivoProduto();
             
             try{
                 cadastro.escreverArquivo(produtoRem, objetoP);
                 for (int i = 0; i < produtoCad.length(); i++) {
                     posicao = i + 1;
                     cadastro.removerDoArquivo(produtoCad, codigoP,imprimirNome.getProdutoEncontrado(),
                             imprimirPrecoVenda.getProdutoEncontrado(),imprimirPrecoCusto.getProdutoEncontrado(),
                               imprimirQuantidade.getProdutoEncontrado(),imprimirFornecedor.getProdutoEncontrado() );
                 }
                 JOptionPane.showMessageDialog(null, "Removido com sucesso!");
                 dispose();
             }catch(IOException except){
                 except.printStackTrace();
             }
         } catch (IOException except) {
                 except.printStackTrace();
         }
         
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutosExcluidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutosExcluidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutosExcluidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutosExcluidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutosExcluidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarcodigop;
    private javax.swing.JTextField buscarp;
    private javax.swing.JButton excluirp;
    private javax.swing.JTextArea infoproduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
