/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author andersonsantos
 */
public class BuscarCliente extends javax.swing.JInternalFrame {
    File clientesCad = new File("./src/Arquivos/clientesCadastrados.txt");
    File clientesRem = new File("./src/Arquivos/clientesRemovidos.txt");
    ManipularArquivo imprimirNome = new ManipularArquivo();
    ManipularArquivo imprimirCpf = new ManipularArquivo();
    String clienteBusca = null;
    String codigoB = null;
    /**
     * Creates new form RemoverCliente
     */
    public BuscarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buscarCod = new javax.swing.JFormattedTextField();
        buscarC = new javax.swing.JButton();
        removerC = new javax.swing.JButton();
        voltarC = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoCliente = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame1.setPreferredSize(new java.awt.Dimension(894, 598));
        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(95, 94, 94));
        jLabel1.setText("BUSCAR CLIENTE");
        jLabel1.setMaximumSize(new java.awt.Dimension(242, 26));
        jLabel1.setMinimumSize(new java.awt.Dimension(242, 26));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(95, 94, 94));
        jLabel2.setText("DIGITE O CÓDIGO DO CLIENTE:");

        buscarCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCodActionPerformed(evt);
            }
        });

        buscarC.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        buscarC.setForeground(new java.awt.Color(95, 94, 94));
        buscarC.setText("BUSCAR");
        buscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCActionPerformed(evt);
            }
        });

        removerC.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        removerC.setForeground(new java.awt.Color(95, 94, 94));
        removerC.setText("REMOVER");
        removerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerCActionPerformed(evt);
            }
        });

        voltarC.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        voltarC.setForeground(new java.awt.Color(95, 94, 94));
        voltarC.setText("VOLTAR");
        voltarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCActionPerformed(evt);
            }
        });

        infoCliente.setEditable(false);
        infoCliente.setColumns(20);
        infoCliente.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        infoCliente.setForeground(new java.awt.Color(95, 94, 94));
        infoCliente.setRows(5);
        jScrollPane2.setViewportView(infoCliente);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buscarCod))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(buscarC)))
                        .addGap(121, 121, 121)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(removerC)
                                .addGap(136, 136, 136)
                                .addComponent(voltarC))
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(buscarCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarC))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removerC)
                    .addComponent(voltarC))
                .addGap(0, 219, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerCActionPerformed
        // TODO add your handling code here:
        int posicao = 0;
        try {
            imprimirNome.mapearArquivo(clientesRem);
            imprimirCpf.mapearArquivo(clientesRem);
            String objetoC = clienteBusca;
            ManipularArquivo cadastro = new ManipularArquivo();
            try{
                cadastro.escreverArquivo(clientesRem, objetoC);
                for (int i = 0; i < clientesCad.length(); i++) {
                    posicao = i + 1;
                    cadastro.removerDoArquivo(clientesCad, 
                                              codigoB, 
                                              imprimirNome.getClienteEncontrado(), 
                                              imprimirCpf.getClienteEncontrado());
                }
                JOptionPane.showMessageDialog(null, "Removido com sucesso!");
                dispose();
            }catch(IOException except){
                except.printStackTrace();
            }
        } catch (IOException except) {
                except.printStackTrace();
        }
    }//GEN-LAST:event_removerCActionPerformed

    private void buscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCActionPerformed
        // TODO add your handling code here:
        int posicao = 0;
        try { 
            FileReader listarFile = new FileReader(clientesCad);
            BufferedReader listarBuff = new BufferedReader(listarFile);
            imprimirNome.mapearArquivo(clientesCad);
            imprimirCpf.mapearArquivo(clientesCad);
            for (int i = 0; i < clientesCad.length(); i++) {
                String linhaL = listarBuff.readLine();
                if(codigoB.equals(linhaL)){
                    posicao = i + 1;
                    imprimirNome.setClienteEncontrado(posicao);
                    imprimirCpf.setClienteEncontrado(posicao + 1);
                    clienteBusca = codigoB + "\n" + imprimirNome.getClienteEncontrado() + 
                                             "\n" + imprimirCpf.getClienteEncontrado();
                    infoCliente.append(clienteBusca);
                    JOptionPane.showMessageDialog(null, "Cliente encontrado!");
                }
            }
            listarBuff.close();
            listarFile.close();
        } catch (IOException except) {
                except.printStackTrace();
        }
    }//GEN-LAST:event_buscarCActionPerformed

    private void buscarCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCodActionPerformed
        // TODO add your handling code here:
        codigoB = buscarCod.getText();
    }//GEN-LAST:event_buscarCodActionPerformed

    private void voltarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_voltarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarC;
    private javax.swing.JFormattedTextField buscarCod;
    private javax.swing.JTextArea infoCliente;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removerC;
    private javax.swing.JButton voltarC;
    // End of variables declaration//GEN-END:variables
}
