/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*;
import java.io.*;
import java.io.IOException;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexandro
 */
public class CadrastoProduto extends javax.swing.JInternalFrame {
    File produtoCad = new File("./src/arquivos/produtosCadastrados.txt");
    Produto produto = new Produto();
    Random rand = new Random();
    /**
     * Creates new form CadrastoProduto
     */
    public CadrastoProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cadrastarprodutop = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomep = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        precocustop = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        precovendap = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        quantidadep = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        cadrastar = new javax.swing.JButton();
        valnomep = new javax.swing.JCheckBox();
        valquantidade = new javax.swing.JCheckBox();
        valcustop = new javax.swing.JCheckBox();
        valvendap = new javax.swing.JCheckBox();
        valfornecedorp = new javax.swing.JCheckBox();
        fornecedorp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(894, 598));

        jLabel1.setBackground(new java.awt.Color(95, 94, 94));
        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N

        cadrastarprodutop.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cadrastarprodutop.setForeground(new java.awt.Color(95, 94, 94));
        cadrastarprodutop.setText("CADRASTAR PRODUTO");

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(95, 94, 94));
        jLabel2.setText("NOME:");

        nomep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomepActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(95, 94, 94));
        jLabel3.setText("PREÇO DE CUSTO:");

        precocustop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precocustopActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(95, 94, 94));
        jLabel4.setText("PREÇO DE VENDA:");

        precovendap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precovendapActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(95, 94, 94));
        jLabel5.setText("FORNECEDOR:");

        jLabel6.setBackground(new java.awt.Color(31, 35, 35));
        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(95, 94, 94));
        jLabel6.setText("QUANTIDADE:");

        quantidadep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadepActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(95, 94, 94));
        jButton1.setLabel("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cadrastar.setBackground(new java.awt.Color(153, 153, 153));
        cadrastar.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        cadrastar.setForeground(new java.awt.Color(95, 94, 94));
        cadrastar.setLabel("CADRASTAR");
        cadrastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadrastarActionPerformed(evt);
            }
        });

        valnomep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valnomepActionPerformed(evt);
            }
        });

        valquantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valquantidadeActionPerformed(evt);
            }
        });

        valfornecedorp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valfornecedorpActionPerformed(evt);
            }
        });

        fornecedorp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cadrastar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(valcustop))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(precocustop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(129, 129, 129)
                                        .addComponent(valvendap)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(precovendap, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(valnomep)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomep, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(valfornecedorp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fornecedorp)))
                                .addGap(0, 116, Short.MAX_VALUE)))
                        .addContainerGap(102, Short.MAX_VALUE))
                    .addComponent(cadrastarprodutop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(99, 99, 99)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(valquantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantidadep, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cadrastarprodutop, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(valnomep)
                    .addComponent(nomep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(valfornecedorp)
                            .addComponent(fornecedorp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(valcustop)
                            .addComponent(precocustop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(valvendap)
                    .addComponent(precovendap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valquantidade)
                    .addComponent(quantidadep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cadrastar))
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("CADRASTAR PRODUTO");
        jLabel5.getAccessibleContext().setAccessibleName("FORNECEDOR");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void precovendapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precovendapActionPerformed
        int numVenda = precovendap.getText().length();
        char[] verificaVenda = precovendap.getText().toCharArray();
        boolean ver = true;
        for(int i =  0; i < verificaVenda.length; i++){
            if(Character.isLetter(verificaVenda[i])){
                ver =false;
            }
        }   
        if(ver == false){
            JOptionPane.showMessageDialog(null, "O preço de custo deve conter apenas numeros, por favor, digite novamente!");
        }
        else{
            produto.setPrecoVenda((int) Long.parseLong(precovendap.getText()));
            if(produto.getPrecoVenda() != 0){
                valvendap.setSelected(true);
            }
            else{
                valvendap.setSelected(false);
            }
        }
        // TODO add your  handling code here:
    }//GEN-LAST:event_precovendapActionPerformed

    private void precocustopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precocustopActionPerformed
        
        int numCusto = precocustop.getText().length();
        char[] verificaCusto = precocustop.getText().toCharArray();
        boolean ver = true;
        for(int i =  0; i < verificaCusto.length; i++){
            if(Character.isLetter(verificaCusto[i])){
                ver =false;
            }
        }   
        if(ver == false){
            JOptionPane.showMessageDialog(null, "O preço de custo deve conter apenas numeros, por favor, digite novamente!");
        }
        else{
            produto.setPrecoCusto((int) Long.parseLong(precocustop.getText()));
            if(produto.getPrecoCusto() != 0){
                valcustop.setSelected(true);
            }
            else{
                valcustop.setSelected(false);
            }
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_precocustopActionPerformed

    private void nomepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomepActionPerformed
        produto.setCodigo(rand.nextInt(9999));
        int numNome = nomep.getText().length();
        char[] verificaNome = nomep.getText().toCharArray();
        boolean ver = true;
        for(int i =  0; i < verificaNome.length; i++){
            if(!Character.isLetter(verificaNome[i])){
                ver =false;
            }
        if(numNome < 2){
        JOptionPane.showMessageDialog(null, "Nome inválido, por favor, digite novamente!");
        }
        else if(ver == false){
            JOptionPane.showMessageDialog(null, "O nome não pode conter numeros ou caracteres especiais, por favor, digite novamente!");
        }
        else{
            valnomep.setSelected(true);
            produto.setNome(nomep.getText());
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_nomepActionPerformed

    private void quantidadepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadepActionPerformed
        int numQuantidadep = quantidadep.getText().length();
        char[] verificaQuantidadep = quantidadep.getText().toCharArray();
        boolean ver = true;
        for(int i =  0; i < verificaQuantidadep.length; i++){
            if(Character.isLetter(verificaQuantidadep[i])){
                ver =false;
            }
        }   
        if(ver == false){
            JOptionPane.showMessageDialog(null, "O preço de custo deve conter apenas numeros, por favor, digite novamente!");
        }
        else{
            produto.setQuantidade((int) Long.parseLong(quantidadep.getText()));
            if(produto.getQuantidade() != 0){
                valquantidade.setSelected(true);
            }
            else{
                valquantidade.setSelected(false);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadepActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cadrastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadrastarActionPerformed
      if(produto.getNome() == null){
            JOptionPane.showMessageDialog(null, "Erro de Nome, por favor, confira.");
        }
        else if(produto.getPrecoCusto() == 0){
            JOptionPane.showMessageDialog(null, "Erro de no preço de venda, por favor, confira.");
        }
       // else if(produto.getQuantidade() == 0){
      //      JOptionPane.showMessageDialog(null, "Erro de de quantidade, por favor, confira.");
      //  }
        else{   
            String objetoP = "\nCODIGO: "+produto.getCodigo()+"\nNOME: "+produto.getNome() + 
                        "\nPREÇO DE CUSTO: "+produto.getPrecoCusto()+"\nPREÇO DE CUSTO: "+produto.getPrecoVenda()+
                        "\nQUANTIDADE: "+produto.getQuantidade()+"\nFORNECEDOR: "+produto.getFornecedor()+"\n";
            ManipularArquivoProduto cadastro = new ManipularArquivoProduto();
            
            
            try {
                cadastro.escreverArquivo(produtoCad, objetoP);
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
                dispose();
                }catch(IOException except) {
                 except.printStackTrace();
                }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cadrastarActionPerformed

    private void valnomepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valnomepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valnomepActionPerformed

    private void fornecedorpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorpActionPerformed
       int numFornecedorp = fornecedorp.getText().length();
        char[] verificaFornecedorp = fornecedorp.getText().toCharArray();
        boolean ver = true;
        for(int i =  0; i < verificaFornecedorp.length; i++){
            if(!Character.isLetter(verificaFornecedorp[i])){
                ver =false;
            }
        }   
        if(numFornecedorp < 2){
        JOptionPane.showMessageDialog(null, "Nome inválido, por favor, digite novamente!");
        }
        else if(ver == false){
            JOptionPane.showMessageDialog(null, "O nome não pode conter numeros ou caracteres especiais, por favor, digite novamente!");
        }
        else{
            valfornecedorp.setSelected(true);
            produto.setFornecedor(fornecedorp.getText());
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedorpActionPerformed

    private void valfornecedorpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valfornecedorpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valfornecedorpActionPerformed

    private void valquantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valquantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valquantidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadrastoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadrastoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadrastoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadrastoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadrastoProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadrastar;
    private javax.swing.JLabel cadrastarprodutop;
    private javax.swing.JTextField fornecedorp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nomep;
    private javax.swing.JFormattedTextField precocustop;
    private javax.swing.JFormattedTextField precovendap;
    private javax.swing.JFormattedTextField quantidadep;
    private javax.swing.JCheckBox valcustop;
    private javax.swing.JCheckBox valfornecedorp;
    private javax.swing.JCheckBox valnomep;
    private javax.swing.JCheckBox valquantidade;
    private javax.swing.JCheckBox valvendap;
    // End of variables declaration//GEN-END:variables
}
