/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;
import BackEnd.*;
import java.io.*;
/**
 *
 * @author andersonsantos
 */
public class ListarVendas extends javax.swing.JInternalFrame {
    File vendasConcluidas = new File("./src/Arquivos/VendasConcluidas.txt");

    /**
     * Creates new form ListarVendas
     */
    public ListarVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imprimirVendas = new javax.swing.JButton();
        voltarVendas = new javax.swing.JButton();
        listaVendas = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(894, 598));

        imprimirVendas.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        imprimirVendas.setForeground(new java.awt.Color(95, 94, 94));
        imprimirVendas.setText("IMPRIMIR");
        imprimirVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirVendasActionPerformed(evt);
            }
        });

        voltarVendas.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        voltarVendas.setForeground(new java.awt.Color(95, 94, 94));
        voltarVendas.setText("VOLTAR");
        voltarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarVendasActionPerformed(evt);
            }
        });

        listaVendas.setBackground(new java.awt.Color(166, 166, 166));
        listaVendas.setEditable(false);
        listaVendas.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        listaVendas.setForeground(new java.awt.Color(1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(95, 94, 94));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTA DE VENDAS CONCLUIDAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addComponent(listaVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(imprimirVendas)
                .addGap(141, 141, 141)
                .addComponent(voltarVendas)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imprimirVendas)
                    .addComponent(voltarVendas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imprimirVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirVendasActionPerformed
        // TODO add your handling code here:
        ManipularArquivo listarV = new ManipularArquivo();
        //String cadas = null;
        try{
            listarV.lerArquivo(vendasConcluidas);
        }catch(IOException except){
            except.printStackTrace();
        }
        listaVendas.append(listarV.getObjetosRetornados());
    }//GEN-LAST:event_imprimirVendasActionPerformed

    private void voltarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarVendasActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_voltarVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton imprimirVendas;
    private javax.swing.JLabel jLabel1;
    private java.awt.TextArea listaVendas;
    private javax.swing.JButton voltarVendas;
    // End of variables declaration//GEN-END:variables
}
